server:
  port: 3000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cstk?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chisato
    password: takina


jwt:
  expired-time: 7*24*60*60
  key: V7wpjLyka93piXKF
